### ISSUE TITLE
CPM v0.0.17e Custom model crash with optifine

### ISSUE THREAD

**Issue by BlazingPL** [tom5454/CustomPlayerModels#121]
CustomPlayerModels-1.16 v0.0.17e

Crash Log: https://paste.ee/p/CBQAg

**Comment by Nyinxie** [comment]
> CustomPlayerModels-1.16 v0.0.17e
> 
> Crash Log: https://paste.ee/p/CBQAg

Another Avali, Woo

**Comment by Nyinxie** [comment]
I too have this issue, Here's a quick dump: 
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 7/28/21 11:16 PM
Description: Batching chunks

java.lang.IllegalStateException: Not building!
	at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:399) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinBufferBuilder,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask$$Lambda$18932/2076623529.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:947) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:735) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$1(ChunkRenderDispatcher.java:192) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.betterf3.json:chunk.ChunkRenderDispatcherAccessor,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$17491/2111122043.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:989) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2116) ~[?:1.8.0_51] {}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_228909_h_(ChunkRenderDispatcher.java:190) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.betterf3.json:chunk.ChunkRenderDispatcherAccessor,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$schedule$4(ChunkRenderDispatcher.java:264) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.betterf3.json:chunk.ChunkRenderDispatcherAccessor,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$17487/189301641.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Nyinxie'/1342, l='ClientLevel', x=-306.51, y=82.00, z=-126.71]]
	Chunk stats: Client Chunk Cache: 729, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (64,64,96), Chunk: (at 0,4,0 in 4,6; contains blocks 64,0,96 to 79,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 49918 game time, 31806 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$3(ChunkRenderDispatcher.java:198) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.betterf3.json:chunk.ChunkRenderDispatcherAccessor,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$17497/1708815855.accept(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2132) ~[?:1.8.0_51] {}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_228909_h_(ChunkRenderDispatcher.java:193) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.betterf3.json:chunk.ChunkRenderDispatcherAccessor,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$schedule$4(ChunkRenderDispatcher.java:264) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.betterf3.json:chunk.ChunkRenderDispatcherAccessor,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$17487/189301641.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1549232808 bytes (1477 MB) / 5975310336 bytes (5698 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 16
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.32.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.32.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.32.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.32.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.32.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.32
	FML Language Providers: 
		javafml@36.1
		minecraft@1
		kotlinforforge@1.14.0
		scorge@3.1.3
