### ISSUE TITLE
Models with animations not exporting

### ISSUE THREAD

**Issue by FuntimeSea676** [tom5454/CustomPlayerModels#28]
I was animating one of the custom models I did, but everytime I click the Export button it does nothing, but when I try to export a model without animations it works fine. Here is the log after pressing the export button:

```
Cliente> [15:04:11] [main/INFO] [STDOUT]: [com.tom.cpm.shared.parts.ModelPartAnimation:lambda$new$4:185]: c_GehtLos_4621.json 1
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: java.lang.NullPointerException
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at com.tom.cpm.shared.parts.ModelPartAnimation.fillArray(ModelPartAnimation.java:240)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at com.tom.cpm.shared.parts.ModelPartAnimation.lambda$new$4(ModelPartAnimation.java:203)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at java.util.ArrayList.forEach(Unknown Source)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at com.tom.cpm.shared.parts.ModelPartAnimation.<init>(ModelPartAnimation.java:170)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at com.tom.cpm.shared.editor.Exporter.exportSkin0(Exporter.java:102)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at com.tom.cpm.shared.editor.Exporter.exportSkin(Exporter.java:55)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at com.tom.cpm.shared.editor.gui.popup.ExportSkinPopup.export(ExportSkinPopup.java:145)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at com.tom.cpm.shared.editor.gui.popup.ExportSkinPopup.lambda$new$10(ExportSkinPopup.java:106)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at com.tom.cpm.shared.gui.elements.Button.mouseClick(Button.java:37)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at com.tom.cpm.shared.gui.elements.GuiElement.mouseClick(GuiElement.java:45)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at com.tom.cpm.shared.gui.elements.Panel.mouseClick(Panel.java:42)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at com.tom.cpm.shared.gui.elements.Panel.mouseClick(Panel.java:42)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at com.tom.cpm.shared.gui.Frame$PopupLayer.mouseClick(Frame.java:128)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at com.tom.cpm.shared.gui.elements.Panel.mouseClick(Panel.java:42)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at com.tom.cpm.shared.gui.elements.Panel.mouseClick(Panel.java:42)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at com.tom.cpm.client.GuiImpl.func_73864_a(GuiImpl.java:161)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at com.tom.cpm.client.GuiImpl.func_146274_d(GuiImpl.java:190)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at java.lang.reflect.Method.invoke(Unknown Source)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at java.lang.reflect.Method.invoke(Unknown Source)
Cliente> [15:04:11] [main/INFO] [STDERR]: [com.tom.cpm.shared.editor.Exporter:exportSkin0:131]: 	at net.minecraft.a.m.main(Unknown Source)
```

Hope you can help me out with this because I really love this mod and would like to see the animations In-game, thank you from beforehand.

**Comment by tom5454** [comment]
Can you post your project file?

**Comment by FuntimeSea676** [comment]
Of course, here it is (had to zip it because github doesn't supports the original format):
[Wehrmacht Sea.zip](https://github.com/tom5454/CustomPlayerModels/files/6055620/Wehrmacht.Sea.zip)
