### ISSUE TITLE
Cannot read properties of undefined (reading 'L')

### ISSUE THREAD

**Issue by A31Nesta** [tom5454/CustomPlayerModels#414]
I'm trying to export a blockbench model with animations and getting this error:
~~~
Error while exporting:
TypeError: Cannot read properties of undefined (reading 'L')
    at com.tom.cpm.blockbench.convert.BlockbenchExport.doExport$lambda$lambda(BlockbenchExport.java:276) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1683806262395:1634:79)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.fixStaged(BlockbenchExport.java:859) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1683806262395:1774:42)
    at mYb (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1683806262395:2111:81)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.getPart(BlockbenchExport.java:1128) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1683806262395:1623:44)
    at mKb (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1683806262395:1618:2383)
    at JLb.KLb [as ye] (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1683806262395:1690:42)
    at com.tom.ugwt.client.JsArrayE.forEachReverse(JsArrayE.java:33) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1683806262395:6022:70)
    at d (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1683806262395:17:47)
    at Array.forEach (<anonymous>)
    at qKb (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1683806262395:1622:664)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.rootWarning$lambda$lambda(BlockbenchExport.java:346) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1683806262395:1626:63)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.rootWarning(BlockbenchExport.java:343) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1683806262395:1733:60)
    at d (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1683806262395:17:47)
~~~

screenshot:
![image](https://github.com/tom5454/CustomPlayerModels/assets/92674974/68f0734c-43e4-4ef3-98e5-0641443ba8c4)

I'm using Blockbench 4.7.1 in Arch Linux installed from the AUR.

**Comment by notabirb1** [comment]
I'm getting this issue as well, BlockBench 4.7.2 on Windows. My model doesn't even have animations, but I'm getting this error anyway.

```
Error while exporting:
TypeError: Cannot read properties of undefined (reading 'L')
    at com.tom.cpm.blockbench.convert.BlockbenchExport.doExport$lambda$lambda(BlockbenchExport.java:276) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1684363215259:1634:79)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.fixStaged(BlockbenchExport.java:859) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1684363215259:1774:42)
    at mYb (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1684363215259:2111:81)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.getPart(BlockbenchExport.java:1128) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1684363215259:1623:44)
    at mKb (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1684363215259:1618:2383)
    at JLb.KLb [as ye] (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1684363215259:1690:42)
    at com.tom.ugwt.client.JsArrayE.forEachReverse(JsArrayE.java:33) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1684363215259:6022:70)
    at d (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1684363215259:17:47)
    at Array.forEach (<anonymous>)
    at qKb (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1684363215259:1622:664)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.rootWarning$lambda$lambda(BlockbenchExport.java:346) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1684363215259:1626:63)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.rootWarning(BlockbenchExport.java:343) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1684363215259:1733:60)
    at d (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1684363215259:17:47)
``` 
This occurs both when exporting (or trying to, anyway) and when viewing the model in the Embedded CPM Editor.
This plugin's never worked quite right for me, but now I can't even export the model anymore.
