### ISSUE TITLE
Cant export my model from blockbench

### ISSUE THREAD

**Issue by naiter321** [tom5454/CustomPlayerModels#431]
![image](https://github.com/tom5454/CustomPlayerModels/assets/131707083/fcb8935c-2e7d-4aed-9e73-446c704cd092)

Error while exporting:
TypeError: Cannot set properties of null (setting 'e')
    at com.tom.cpm.blockbench.convert.BlockbenchExport.convertUV(BlockbenchExport.java:1073) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:1629:738)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.convert(BlockbenchExport.java:998) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:1626:282)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.makePart(BlockbenchExport.java:1191) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:1729:124)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.finishConvert$lambda(BlockbenchExport.java:1177) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:1728:19)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.finishConvert(BlockbenchExport.java:1176) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:1734:41)
    at com.google.gwt.emul.java.util.ArrayList.forEach(ArrayList.java:175) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:2121:81)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.finishConvert(BlockbenchExport.java:1176) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:1727:17)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.doExport(BlockbenchExport.java:326) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:1694:42)
    at com.google.gwt.emul.java.util.stream.StreamImpl.tryAdvance$lambda(StreamImpl.java:426) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:6727:291)
    at com.google.gwt.emul.java.util.stream.StreamImpl.tryAdvance(StreamImpl.java:423) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:6730:42)
    at com.google.gwt.emul.java.util.Spliterators.tryAdvance(Spliterators.java:462) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:6476:48)
    at com.google.gwt.emul.java.util.Spliterators.tryAdvance(Spliterators.java:458) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:6478:171)
    at com.google.gwt.emul.java.util.stream.StreamImpl.tryAdvance(StreamImpl.java:421) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:6729:77)
    at com.google.gwt.emul.java.util.Spliterator.forEachRemaining(Spliterator.java:51) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:6474:105)
    at com.google.gwt.emul.java.util.Spliterator.forEachRemaining(Spliterator.java:50) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:6484:36)
    at com.google.gwt.emul.java.util.stream.StreamImpl.forEachOrdered(StreamImpl.java:557) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:6704:30)
    at com.google.gwt.emul.java.util.stream.StreamSupport.stream(StreamSupport.java:74) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:1630:1187)
    at com.tom.cpm.blockbench.convert.ProjectConvert.prepExport$lambda$lambda(ProjectConvert.java:63) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:1874:42)
    at com.tom.cpm.blockbench.convert.ProjectConvert.prepExport$lambda(ProjectConvert.java:60) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:1900:40)
    at com.tom.cpm.web.client.render.RenderSystem.withContext(RenderSystem.java:1239) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:5908:67)
    at com.tom.cpm.blockbench.convert.ProjectConvert.prepExport$lambda(ProjectConvert.java:60) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:1873:23)
    at com.tom.cpm.blockbench.convert.ProjectConvert.prepExport(ProjectConvert.java:59) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:1899:55)
    at com.google.gwt.dev.jjs.intrinsic.com.google.gwt.lang.Runtime(Runtime.java:165) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:17:47)
    at new Promise (<anonymous>)
    at com.tom.cpm.blockbench.convert.ProjectConvert.prepExport(ProjectConvert.java:59) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:1898:47)
    at com.tom.cpm.blockbench.util.PopupDialogs.runTaskWithWarning(PopupDialogs.java:144) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:2028:32)
    at com.tom.cpm.blockbench.convert.ProjectConvert.exportWithWarnings(ProjectConvert.java:55) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:1866:217)
    at com.tom.cpm.blockbench.format.CPMCodec.init(CPMCodec.java:48) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:1932:52)
    at com.google.gwt.dev.jjs.intrinsic.com.google.gwt.lang.Runtime(Runtime.java:165) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:17:47)
    at com.tom.cpm.blockbench.BBActions.load$lambda(BBActions.java:81) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:1550:63)
    at com.google.gwt.dev.jjs.intrinsic.com.google.gwt.lang.Runtime(Runtime.java:165) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686344076572:17:47)
    at Action.trigger (file:///C:/Users/Barsyk%20Barsykov/AppData/Local/Programs/Blockbench/resources/app.asar/js/interface/actions.js:314:10)
    at HTMLLIElement.<anonymous> (file:///C:/Users/Barsyk%20Barsykov/AppData/Local/Programs/Blockbench/resources/app.asar/js/interface/menu.js:308:9)
    at HTMLLIElement.dispatch (file:///C:/Users/Barsyk%20Barsykov/AppData/Local/Programs/Blockbench/resources/app.asar/lib/jquery.js:2:43064)
    at v.handle (file:///C:/Users/Barsyk%20Barsykov/AppData/Local/Programs/Blockbench/resources/app.asar/lib/jquery.js:2:41048)

**Comment by donaldjuniortrump** [comment]
i get the same error. tom will hear from my lawyers
