### ISSUE TITLE
[1.7.10] The player model cannot be changed when running with LOTRmod

### ISSUE THREAD

**Issue by OAO-233** [tom5454/CustomPlayerModels#460]
As mentioned in the title, I have excluded all other mods and kept only two. The problem still exists, but I do not want to remove either of these mods,Is there a way around this?

Attempts to apply the model or enter CPM command are invalid and errors are reported.
When trying to apply the model：
```
[17:55:37] [Server thread/ERROR]: Exception while processing cpm packet: cpm_net:set_skin
java.lang.NullPointerException
	at com.tom.cpm.shared.network.packet.SetSkinC2S.handle(SetSkinC2S.java:21) ~[SetSkinC2S.class:?]
	at com.tom.cpm.shared.network.IC2SPacket.handle0(IC2SPacket.java:14) ~[IC2SPacket.class:?]
	at com.tom.cpm.shared.network.IC2SPacket.handle(IC2SPacket.java:9) ~[IC2SPacket.class:?]
	at com.tom.cpm.shared.network.IPacket.lambda$handleRaw$0(IPacket.java:13) ~[IPacket.class:?]
	at com.tom.cpm.shared.network.NetHandler.execute(NetHandler.java:405) ~[NetHandler.class:?]
	at com.tom.cpm.shared.network.IPacket.handleRaw(IPacket.java:13) ~[IPacket.class:?]
	at com.tom.cpm.shared.network.NetHandler.processPacket(NetHandler.java:194) [NetHandler.class:?]
	at com.tom.cpm.shared.network.NetHandler.receiveServer(NetHandler.java:180) [NetHandler.class:?]
	at com.tom.cpmcore.CPMASMServerHooks.onServerPacket(CPMASMServerHooks.java:16) [CPMASMServerHooks.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147349_a(NetHandlerPlayServer.java) [nh.class:?]
	at net.minecraft.network.play.client.C17PacketCustomPayload.func_148833_a(SourceFile:65) [iz.class:?]
	at net.minecraft.network.play.client.C17PacketCustomPayload.func_148833_a(SourceFile:9) [iz.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```

When trying to execute a command
```
[17:55:50] [Server thread/ERROR]: Couldn't process command: 'cpm setskin -r @p'
java.lang.NullPointerException
	at com.tom.cpm.shared.network.NetHandler.setSkin(NetHandler.java:218) ~[NetHandler.class:?]
	at com.tom.cpm.shared.CommandCPM.executeSkinChange(CommandCPM.java:178) ~[CommandCPM.class:?]
	at com.tom.cpm.shared.CommandCPM.lambda$register$2(CommandCPM.java:44) ~[CommandCPM.class:?]
	at com.tom.cpl.command.StringCommandHandler$CommandImpl.execute(StringCommandHandler.java:170) ~[StringCommandHandler$CommandImpl.class:?]
	at com.tom.cpm.common.Command$Cmd.func_71515_b(Command.java:42) ~[Command$Cmd.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```

Full log: https://gist.github.com/OAO-233/6622c176d71a08cb6516debe65558bec

**Comment by tom5454** [comment]
The LOTRmod is replacing the NetHandlerPlayServer of the player and deletes the CPM data, that causes this issue.
