### ISSUE TITLE
How to disable checking for updates?

### ISSUE THREAD

**Issue by FurryRbl** [tom5454/CustomPlayerModels#611]
I hope to add a configuration item that disables checking for updates, because it is impossible to connect to `raw.githubusercontent.com` in mainland China, which will seriously slow down the game startup speed and report an error:

```
[22:24:17] [pool-4-thread-1/WARN]: CPM version check failed
java.net.UnknownHostException: raw.githubusercontent.com
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[?:?]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.base/java.net.Socket.connect(Socket.java:757) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531) ~[?:?]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636) ~[?:?]
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:?]
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377) ~[?:?]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1285) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1126) ~[?:?]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1678) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1602) ~[?:?]
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223) ~[?:?]
	at com.tom.cpm.shared.io.HTTPIO.getResponse(HTTPIO.java:37) ~[CustomPlayerModels-Fabric-1.20.5-0.6.16e.jar:?]
	at com.tom.cpm.shared.util.VersionCheck.run(VersionCheck.java:47) ~[CustomPlayerModels-Fabric-1.20.5-0.6.16e.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by tom5454** [comment]
The update checker is running on a separate thread and doesn't effect loading times. I'll add a config option in the next version.
