### ISSUE TITLE
[0.0.11bc] Bug with invisible textures on character while testing in "Test Ingame" phase (IDK if export is bugged)

### ISSUE THREAD

**Issue by Nues** [tom5454/CustomPlayerModels#63]
![image](https://user-images.githubusercontent.com/10713596/114297153-03c89a80-9a7d-11eb-9365-dd505184c6ae.png)
![image](https://user-images.githubusercontent.com/10713596/114297159-09be7b80-9a7d-11eb-81b3-d432d69c8a2f.png)
![image](https://user-images.githubusercontent.com/10713596/114297186-2ce92b00-9a7d-11eb-99f6-75e0ee9e4669.png)

There seems to be no misalignments with all the limbs.

The fist is parented to forearm (forearm has a sibling also called shoulder/upperarm), which is parented to a different shoulder, which is parented to the vanilla limb.

There seems to be a invisible patch on all of my arms.

**Comment by Nues** [comment]
IN ADDITION: I have tried to export the 128x128 skin with a gist, but no "Successfully exported X" message, and the export seems to not happen.

**Comment by tom5454** [comment]
Please post your project file. (You have to zip it to upload it to github).

**Comment by Nues** [comment]
Here it is.
[MothDude.cpmproject.zip](https://github.com/tom5454/CustomPlayerModels/files/6291665/MothDude.cpmproject.zip)

**Comment by tom5454** [comment]
Your texture is built for 6x8x6 part and you are only using 5x8x5 part, thats why it shows up weirdly in game. In the editor your part has a size of 5.000001 (somehow?) for the width and depth which maps a 6x8x6 texture instead the 5x8x5. Go over your parts and type in 5 into the text box to set them to the correct value.

I also tested the export and it worked fine for me. Please post your minecraft log.

**Comment by Nues** [comment]
Sorry for the messy paste, minecraft logs don't seem to save as files without copy/pasting them. This is an excerpt pulled from the STDOUT AND STDERR blocks of the log. If you want the whole log, let me know.

`9:21:59.725
STDOUT
Render thread
[com.tom.cpm.shared.parts.ModelPartAnimation:lambda$new$7:198]: v_walking_MothWalk_6528.json 111111
19:21:59.727
STDOUT
Render thread
[com.tom.cpm.shared.parts.ModelPartAnimation:lambda$new$7:198]: v_riding_MothRide_6623.json 111111
19:21:59.727
STDOUT
Render thread
[com.tom.cpm.shared.parts.ModelPartAnimation:lambda$new$7:198]: c_MothWings_8699.json 1
19:21:59.728
STDOUT
Render thread
[com.tom.cpm.shared.parts.ModelPartAnimation:lambda$new$7:198]: v_standing_MothStand_3716.json 111111
19:21:59.728
STDOUT
Render thread
[com.tom.cpm.shared.parts.ModelPartAnimation:lambda$new$7:198]: v_running_MothRun_5681.json 111111
19:21:59.728
STDOUT
Render thread
[com.tom.cpm.shared.parts.ModelPartAnimation:lambda$new$7:198]: v_swimming_MothSwim_4743.json 111111
19:21:59.729
STDOUT
Render thread
[com.tom.cpm.shared.parts.ModelPartAnimation:lambda$new$7:198]: v_sneaking_MothSneak_5443.json 111111
19:21:59.729
STDOUT
Render thread
[com.tom.cpm.shared.parts.ModelPartAnimation:lambda$new$7:198]: v_sleeping_MothSleep_7221.json 111111
19:21:59.789
STDOUT
Render thread
[com.tom.cpm.shared.editor.Exporter:handleGistOverflow:348]: Uy1GRkYAAPAE/Vb2rvau9q4AAAAAAAAAAQAgHhQABVTgCPVY/Vb4Av1WAAAAAAAAAAAAAAAeFAAAAAVUAAD9VvgC/VYAAAAAAAALAAAAAB4UAAAACqgAAP1W+AL9VgAAAAAAAAsAAAAAHhQA+ALgCPVY/Vb4Av1WAAAAAAAAAAAAAAAeFAAAAAVUAAD9VvgC/VYAAAAAAAAOAAAAAB4UAAAACqgAAP1W+AL9VgAAAAAAAA4AAAAAgkZK/qv1WAGZ8AT2rvVYAAAAAAAAAQEeADY2NgFV+AIH/vjP+M/4zx//GOPqqREA////RihG9q31WAAA9q76rPatAAAf/wiIEQD///8yMjIOpvVYAAD5WPlY+VcOOB//3/8RAP///zIyMvKu9VgAAPlY+Vj5V/HGH/8f/xEA////RihGC/z1WAAA9q76rPatALYf//d2EQD///9QUDIBVfgCAAD1WPVZ+AIHHPjiH/8RARhYjL4A9iXyrgrs2rQAAAAAAAAAAAAAEQEAAIy+AAHd8q4K7AAAAAAAAAAAAAAAABH/AAA2NjYBEPng9Vj4z/jP+M8f/2cc6qkRAP///4y+AAFVAAAKY9q0AAAAAAAAAAAAABEBAACMvgAB3QAACmMAAAAAAAD//wAAAAAR/wAAbjw8/qsGIP948q74AvgCAtj//wAAAQEeD248PAAAAAACZfKu+AL4AvjiAAD//x0BHhtuPDwAAAFVAMzyrvgC+AL9JgAA//8dAR4bbjw+AAANlv808q74AvgC/SYAAP//HQEeJ0E0QQ1S6zkAAPd6+RP3egAAAADf/wIBABM8UDwAAAVUAAD4AvVY+AIAAAAAAAAhAQAuMlAyAAAapACI+M/1WPjP//8AAP//IQEDSTctN/7wBiD+8PjP+M/4z/////8AACMBAD1BNEEH/gVUAAD3evkT93oAAAAA//8CAQATPFA8AAAFVAAA+AL1WPgCAAAAAAAAJQEALjJQMgAAGqQAiPjP9Vj4z///AAD//yUBA0k3LTf+8AYg/vD4z/jP+M//////AAAnAQA9QDRA8q7qsAAA93r5E/d6/////x//A/8AEzxQPAAABVQAAPgC9Vj4Av//AAAAACkBAC4yUDIAiBqkAET4z/VY+M///wAAAAAp/wNJNy03/7wGIP7w+M/4z/jP//8AAAAAK/8APUA0QPZpBVQAAPd6+RP3ev////8AAAP/ABM8UDwAAAVUAAD4AvVY+AL//wAAAAAtAQAuMlAyAIgapABE+M/1WPjP//8AAAAALf8DSTctN/+8BiD+8PjP+M/4z///AAAAAC//AD08WjwDMvwBAAD4AvVZ+AIAAAAAAAAE/xhINlo2ARAARACI+AL1WfgCAAAAAAAAMf8wSDZeNgP/E/oAiPgC9Vn4AgAAAAAAAAQBAFY8Wjz8zvwBAAD4AvVZ+AIAAAAA//8FARhINlo2AIgARACI+AL1WfgCAAAAAP//NAEwSDZeNv2bE/oAiPgC9Vj4AgAAAAAAAAUBAFYBAQQFzQgAgACAxwiJUE5HDQoaCgAAAA1JSERSAAAAgAAAAIAIBgAAAMM+YcsAAAQOSURBVHja7Z27bhNBGEa3CkqoKMI1ojARoEURBRIKJUoViYIULskLoO3zBNTINRKdC7dIfhJ3eQDKvAGDZ/bimb3Is87seGf3HGlie+3Ekb8z/1wyUqLIDlFqnfJ7/R6+WgR24cenU28SNIWlgwA+kp9tAhfLWEkQn8beBSj4+2vTHIlAyg3Bq3Ybq+DlbSHCrV8BKsGX2z0lIO268FXo0yJ8vaXDQexFgK3hO5CAxCvhT42er0TQHy/9VQAE8B1+3tPzKrDMbo3hYCqyuQECDFKAWSl0dTtNK4N2ra8C5PcV8yhtpfv660i+HL4SIBKViWBx300FsOmdPioAFWLNKslC14PX21JVgX+6JAgwEBaJGfYqiporgcMhwDaArpeBoxcg7/1G8LPq47QK+K0APjaCECDZhC1vZVtoj40qoK0K9rHf38VWMAIkZvg5lQrgeAXQKvRsBm9cL83qEWDXOYDe29Po1Vfjuj40XPoToO2SDgHuWQH03l8p/+smJ4xd/z4EuA8Jsl6+iLShoDQHWCV+PkwE2KcEWo9faKXfV/gI0IPhQFWBJGuXfsNHgJ5RNylDAAToFOMPO/OalUDLGT8p9lSAbUs/VwIgRmACGOv/ubn7pz9GgAELUNfjqQAjGwK2CcBh0BEMAWUh6p5HAI/LrrYC1AXV1XIPAQITgH0ABEAABECAYATYdQJYlgABeoawxNV7IEBIctgcya5pvoYkBAhYAJaBPePu7k4gACAAIAAgACAAIXfSXMtBgggArgT4/P6naufvfoizyXcxef5VvH35zQjw7JW8frW+fi0+rV+Xfw8CDEQAGf6HNzfi5PhCHD54KuT+gAxbPi+vy8cHB8fiyaOPSpLzTAIEGMgQIAOVnDy+EA8PX6hWCPD6priWb/Gr1zMEDGsOIEOVpV8OAZNnV8ZzUoZ0aLhuHT4CMAlEgKGK4fK9XQmASAiAACEKYHvse9sBE1c/BwE8C2ATnm1orn4OAngWIA/PxRG1ro66IUDHAsAAloF8wggACAAIAAgACAAIAAgAAD3nz5dI1LUo+w+iNddhTALoDQGoAAgwFgFyCRBg5AIwBFABqABDD9pF4xMOXICmSZ/N8IAAYVAJzQjz6Ei1XQSIOG0blgCVMLPgdQG0nm3cb3qej3cAAuw49iPAmCaHrd8gG1oqDRDASVnjr5b9FqA4l48ACIAADAEIgAAIEETQrcXIgm0s+Q3N9vUcaUMABEAABEAABEAABEAABEAABAhWgK3/uQwBwtsIEi2w3T42QIBAdwIBAQABIEQBjDOC+blBQABgGcjQgAAIgAAIgAAIgAAIgAAIgACAADCgDR8EQAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADYK/8BqwlajknSNlgAAAAASUVORK5CYIIHDQAAAO1aAAAAAAAAAAAHDQIAAP1WAAAAAAAAAAAHDQMAAP1WAAAAAAAAAAAHDQQAAP1WAAAAAAAAAAAHDQUAAP1WAAAAAAAAAAAICgEYAAADdgN2AqoICgEZAAADdgN2AqoICgEbAAACqgO6AqoICgEcAAACqQO6AqoKpyQBAwIAAAcYABMEA+gtNC8zISsdNgMFBCkjJTERJwIfCAIAPwQaAAD28gAAAqr28gAAAAD28gAA/Vb28gAAAAADGgAA/////wqqHHH//wqq/////wqq443//wqqBBoAAfzO/AH5WPzO/AEAAPzO/AEAAPzO/AEAAAMaAAHf/wAA//8AAAAA//8AAAAA//8AAAAA//8EGgACAAAapAAAAAAX+v6rAMwapAAAAAAQhPVYAxoAAgAAAAAAtvVUAAAAAAAAAAAAANjiAAAAAAQaAAMD/xP6BVQD/xP6AIgD/wv87rAD/xP6AIgDGgADBxwAAAAAAAAAAAAA8cYAAAAAAAAAAAAABBoABAf+6zn6rAf+6zkAAAf+6zkFVAf+6zkAAAMaAATjjQAA3/8AAAAA3/8ccQAA3/8AAAAA3/8EGgAFAAAZTv6sAAAapAAAAAASpvatAAAapAAAAxoABfjiAAAAAAAAAAAAAN//AAAAAAAAAAAAAAMaAAYC2AOOAAAC2AAAAAAC2PxwAAAC2AAAAAAEGgAH/ZsL/O6w/ZsT+gCI/ZsT+gCI/ZsT+gCIAxoAB/HGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQaAAjyrgVUAADyrgVUAADyrgVUAADyrgVUAAAEGgAJ+vEf+AAA+vEf+PlX+vEf+AAA+vEf+AapAxoACQAAAAAAAOqpAAAAAAAAAAAAABjjAAAAAAQaAAoFDx/4AAAFDx/4BqgFDx/4AAAFDx/4+VcDGgAKAAAAAAAAGOMAAAAAAAAAAAAA6qkAAAAABBoAC/gC6zkFVPgC6zkAAPgC6zn6rPgC6zkAAAMaAAsccf//H////wAAH//jjQAAH////wAAH/8EGgAMAAASpva0AAAapAAAAAAZTv6rAAAapAAAAxoADN//AAAAAAAAAAAAAPjiAAAAAAAAAAAAAAQaAA0GZAAA/VYGZAAAAAAGZAAAAqoGZAAAAAADGgANAAAAAPVU440AAPVUAAAAAPVUHHEAAPVUBBoADgMy/AEAAAMy/AEAAAMy/AH5WAMy/AEAAAMaAA4HHAAAAAD//wAAAADf/wAAAAAAAAAAAAADGgAPAAAHHAAA//8AAAAAAAD44gAA//8AAAAABBoAEAAAGU4AiAAAEIT1WQAAGqQAAAAAF/r9VgMaABD//wAAAiLY4gAAAAD//wAAAAD1VAAAAAAEGgARD/wFVAAAD/wFVAAAD/wFVAAAD/wFVAAABBoAEgAAAVUAzP6rAVUAzAAAAVUAzAAAAVUAzAMaABL9JgAA//8AAAAA///9JgAA///9JgAA//8BAwgBAAcNAQgBA+gtIyUhKwUEKQgCAT8DCAEA3////wAABAgBAfVZEIQAiAMIAQH//wAALjgDCAEC3/8AAP//BAgBAwf++ALtWgMIAQPf/wqqGOMECAEECIYRlQBEAwgBBAAAAADf/wQIAQX68Rf6+qwDCAEFw40KqgAABAgBBgUPF/r6rAMIAQbDjfVUAAAECAEH+AL4Au1aAwgBB/HG9VTqqQENAAIACU1vdGhXaW5ncwcJAgQBA+gcGRsYCAICAQQIAgAAAAVUB/4DCAIAAtj1VPVUBAgCAQFUB/4H/gMIAgEKqgAAv/8ECAICAqkFVAf+AwgCAgLYCqoKqgQIAgMBmf1WB/4DCAIDCqoAAD//AQMBAwAHEQMMAhOILS8jJSErHQUnBBEpCAIDPwQOAwD28gAA+qz28gAA+qwDDgMA/////wqq///44gAABA4DAQAAGqQAAAAAGqQAAAMOAwEAAAAAAAD//wAAAAAEDgMCAAAapAAAAAAapAAAAw4DAgAAAAAAAAAAAAAAAAQOAwMJDgAABVQJDgBEBVQDDgMDAAAAAPVUAAD44v//BA4DBAqn6zkFVAqn630FVAMOAwQKqgAA5xsRxwAA8cYEDgMFAAAapAAAAAAapAAAAw4DBQAAAAAAAAAAAAAAAAQOAwb+qwYg/3j+qwZk/3gDDgMGAtj44gAAAtjxxgAABA4DB/rxHU4AAPrxHU7/eAMOAwcAAPjiAAAAAP//AAAEDgMIAAAapAAAAAAapAAAAw4DCAAAAAAAAP//AAD//wQOAwkFDx1OAVUFDx1OAd0DDgMJAAD44gAAAAD//wAABA4DCv6r9VgBmf6r9Z0BmQMOAwoAAPjiAAAAAPSeAAAEDgML9RTrOfqs9RTrOfqsAw4DC/VU//8Y4+43//8OOAEDAwQABxgEEwQDIC00LzMhKx02AwUEKSMlCjERJwIIAgQ/BBoEAPbyAAD4AvbyAAAAAPbyAAACqvbyAAAAAAMaBADVVP//CqoAAP//Cqoqqv//CqoAAP//CqoEGgQB/M78Afmc/M78Af+8/M78AQf+/M78AQVUAxoEAdVUAAD///jiAAD//xVVAAD//yqqAAD//wQaBAIAAA/8+qwAABqkAAAAABVQ/VYAABqkAAADGgQC1VQAAAAAAAAAAAAA6qkAAAAAAAAAAAAABBoEAwP/DMkVUAP//vAVUAP/CVPoBgP/Eqb7PAMaBAMf/wAAAABKqgAAAADccAAA/0j44gAAAAAEGgQECqjqsAVUCqjqsAAACqjqsPKuCqjqsAAAAxoEBB//AADf/wAAAADf/9//AADf/wAAAADf/wQaBAUAAA/8+qwAABqkAAAAABVQ/VYAABqkAAADGgQF1VQAAAAAAAAAAAAA6qkAAAAAAAAAAAAABBoEBv6rBZj/NP6rBZj/NP6rBZj/NP6rBZj/NAMaBAYKqvjiAAAKqv//AAAKqgccAAAKqv//AAAEGgQH/ZsJUugG/ZsSpfzO/d8MyRVQ/Zv+8BVQAxoEB9xwAAAAAPjiAAAAAB//AAAAAEqqAAAAAAQaBAjyrgVUAADyrgVUAADyrgVUAADyrgVUAAAEGgQJ+vEf+AAA+vEf+AAA+vEf+AAA+vEf+AAAAxoECf//AAAAAP//AAAAAP//AAAAAP//AAAAAAQaBAoFDx/4AAAFDx/4AAAFDx/4AAAFDx/4AAADGgQK//8AAAAA//8AAAAA//8AAAAA//8AAAAABBoEC/VY6rDyrvVY6rAAAPVY6rAFVPVY6rAAAAMaBAvf////H/8AAP//H/8f////H/8AAP//H/8EGgQMAAAVUP1WAAAapAAAAAAP/PqsAAAapAAAAxoEDOqpAAAAAAAAAAAAANVUAAAAAAAAAAAAAAQaBA0JDgAAAqoJDgAAAAAJDgAA+AIJDgAAAAADGgQNKqoAAPVUAAAAAPVU1VQAAPVUAAAAAPVUBBoEDgAA8AT1WAAA8AT1WAAA8AT1WAAA8AT1WAQaBA8DMvwBB/4DMvwBBVQDMvwB+ZwDMvwB/zQDGgQPFVUAAAAAKqoAAAAA1VQAAAAA+OIAAAAABBoEEP6r9Vj9Vv6r9Vj9Vv6r9Vj9Vv6r9Vj9VgMaBBAKqvHGAAAKqgAAAAAKqg44AAAKqgAAAAAEGgQRAAAVUP1WAAAapAAAAAAP/PqsAAAapAAAAxoEEeqpAAAAAAAAAAAAANVUAAAAAAAAAAAAAAQaBBINUgVUAAANUgVUAAANUgVUAAANUgVUAAABAwUFAAcRBQwIBOItJSEFAwQCKSMdESsIAgU/AzIFAPVU//8AAP////8AAAqq//8AAP////8AAPVU//8AAP////8AAAqq//8AAP////8AAAMyBQH1VAAA//8AAAAA//8KqgAA//8AAAAA///1VAAA//8AAAAA//8KqgAA//8AAAAA//8EMgUCDVLt4wAACqjrOQKqB/7rOQf+CqjrOQKqDVLojwAADVLrOf1WB/7rOfgCCqjrOf1WAzIFAgAAv//f/90mmOL1VL//f////5//n//qqX//v////5//9VQHHL//AAD//+cb6T3qqQQyBQP68R/4Aqr68R/4AAD68R/4/Vb68R/4AAD68R/4Aqr68R/4AAD68R/4/Vb68R/4AAADMgUDCqoAAAAAAAAAAAAA9VQAAAAAAAAAAAAACqoAAAAAAAAAAAAA9VQAAAAAAAAAAAAABDIFBPKuBVQAAPKuBVQAAPKuBVQAAPKuBVQAAPKuBVQAAPKuBVQAAPKuBVQAAPKuBVQAAAQyBQUFDx/4AqoFDx/4AAAFDx/4/VYFDx/4AAAFDx/4AqoFDx/4AAAFDx/4/VYFDx/4AAADMgUFCqoAAAAAAAAAAAAA9VQAAAAAAAAAAAAACqoAAAAAAAAAAAAA9VQAAAAAAAAAAAAABDIFBg1SBVQAAA1SBVQAAA1SBVQAAA1SBVQAAA1SBVQAAA1SBVQAAA1SBVQAAA1SBVQAAAQyBQfyrugGAAD1WOqw/Vb4Auqw+AL1WOqw/Vbyru1aAADyruqwAqr4AuqwB/71WOqwAqoDMgUHf/8//wAAn/8Kqgccv////wAA3/8ccQ44AAA//x//3/9f/w44v/9//wAAn/9f/xVVBDIFCAAAGqQAiP6sGU4AiPgDEqYAiAAAGqQAiAAAGqQAiAAAGqQAiAAAGqQAiAAAGqQAiAMyBQj//wAA/////wAABxwAAP//H////wAA/////wAA/////wAA/////wAA/////wAA//8DMgUJAtj//wAAAtj8cAAAAtjxxgAAAtj8cAAAAtj//wAAAtgDjgAAAtgOOAAAAtj//wAAAzIFCgAAAAAAAAAA+OIAAAAA6qkAAAAA+OIAAAAAAAAAAAAABxwAAAAAFVUAAAAABxwAAAQyBQsAiBqkAEQAiBqkAEQAiBqkAEQAiBqkAEQAiBqkAEQB3RlOAEQH/hKmAIgAiBqkAEQDMgUL//8AAAAA//8AAAAA//8AAAAA//8AAAAA//8AAAAA//8AAPji/////9////8AAAAAAQMEBgAHFQYQAgu4LTQvMyErHTYAKSMlIDERJwgCBj8EDgYA+AIFVP6s+AIH/v6sAw4GANxw//8AANji//8AAAQOBgH8zvwBAAD8zgAA/VYDDgYB9VQAAP//6qkAAP//BA4GAgAAGqQAAAAAGqQAAAMOBgIAAAAAAAAAAAAAAAAEDgYDA/8SpgapA/8R2QXcAw4GAwqqAAAAABYLAAAAAAQOBgQNUvKuBVQNUvVYBVQDDgYE2OIAAPji1VQAAPjiBA4GBQAAFqX+sgAAFqX8kQMOBgX1VAAAAADuNwAAAAAEDgYG/qsGIP94/qsIyv94Aw4GBgWw/HAAAAT6/HAAAAQOBgf9mxJh/Vf9mxJh+AMDDgYH/HAAAAAAAAAAAAAABA4GCAAA+qz4AgAA/Vb4AgQOBgn1WPKu+AL1WPVY+AIDDgYJ2OL//wcc1VT//wccBA4GCgAAFqX+sgAAFqT8igMOBgr1VAAAAADuNwAAAAAEDgYLCqgH/gf+CqgKqAf+Aw4GC9HGAAD//844AAD//wQOBgwAAA2WAAAAAA2WAAADDgYM5a8DjgAA5a8DjgAABA4GDQMy/AEAAAMyAAAAAAMOBg0KqgAAAAADjgAAAAAEDgYO/qv4AgGZ/qv6rAGZAw4GDgOO+OIAAAAA+OIAAAQOBg/6rBVQAIj6rBKmAIgDDgYPAAAAABVVAAD//xxxAQMHBwAHEwcOAh9ALS8zIR0FAAQpIyYlEScIAgc/BA4HAPVY9VjoBvVY9VjoBgMOBwAdJ///AAAdJ///AAAEDgcBAIgXcf3fAIgXcf3fAw4HAfHGAAAAAPBa//8AAAQOBwID/w1RA3YD/w1RA3YDDgcCP/8AAAAAP/8DjgAABA4HAw1S9VjStg1S9VjStgMOBwMVVQAAEccVVQAAFVUEDgcE/qv7NegG/qv7NegGAw4HBEqq/////044/////wQOBwX68QAA+AL68QAA+AIDDgcF//8AAAAA//8AAAAABA4HBgAAAADQDAAAAADQDAMOBwZOOAAAAABVVQAAAAAEDgcHBQ8AzPFZBQ8AzPFZAw4HB+43AAAAAO43AAAAAAQOBwjyrvVY0rbyrvVY0rYDDgcIH////+ONH0n//9//BA4HCf1XBqjze/1XBqjzewMOBwmY4v//7YGY4v//440DDgcKAAAAAPVUAAAAAPVUBA4HCwqo+ALoBgqo+ALoBgMOBwsAAP//GOMAAP//Gk8EDgcM/qv+I9gL/qv+I9gLAw4HDEqqAAAAAE44AAAAAAQOBw0AABFQ/AEAABFQ/AEDDgcN3/8Nggcc3/8NggccCQIAPwAAAK07`





`19:22:30.205
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: java.lang.ArrayIndexOutOfBoundsException: 4096
19:22:30.205
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at com.tom.cpl.util.Image.getRGB(Image.java:48)
19:22:30.205
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at com.tom.cpm.shared.io.SkinDataOutputStream.<init>(SkinDataOutputStream.java:24)
19:22:30.206
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at com.tom.cpm.shared.editor.Exporter.lambda$exportSkin$0(Exporter.java:71)
19:22:30.206
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at com.tom.cpm.shared.editor.Exporter$Result.get(Exporter.java:377)
19:22:30.206
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at com.tom.cpm.shared.editor.Exporter.lambda$writeOut$11(Exporter.java:225)
19:22:30.206
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at com.tom.cpm.shared.editor.gui.popup.CreateGistPopup.lambda$null$1(CreateGistPopup.java:49)
19:22:30.206
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at com.tom.cpm.shared.editor.gui.popup.CreateGistPopup.checkURL(CreateGistPopup.java:84)
19:22:30.206
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at com.tom.cpm.shared.editor.gui.popup.CreateGistPopup.lambda$new$2(CreateGistPopup.java:48)
19:22:30.206
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at com.tom.cpl.gui.elements.Button.mouseClick(Button.java:37)
19:22:30.207
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at com.tom.cpl.gui.elements.GuiElement.mouseClick(GuiElement.java:47)
19:22:30.207
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at com.tom.cpl.gui.elements.Panel.mouseClick(Panel.java:46)
19:22:30.207
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at com.tom.cpl.gui.elements.Panel.mouseClick(Panel.java:46)
19:22:30.207
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at com.tom.cpl.gui.Frame$PopupLayer.mouseClick(Frame.java:131)
19:22:30.207
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at com.tom.cpl.gui.elements.Panel.mouseClick(Panel.java:46)
19:22:30.207
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at com.tom.cpl.gui.elements.Panel.mouseClick(Panel.java:46)
19:22:30.207
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at com.tom.cpm.client.GuiImpl.func_231044_a_(GuiImpl.java:194)
19:22:30.208
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87)
19:22:30.208
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427)
19:22:30.208
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85)
19:22:30.208
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175)
19:22:30.208
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
19:22:30.208
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174)
19:22:30.208
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
19:22:30.209
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
19:22:30.209
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3050)
19:22:30.209
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102)
19:22:30.209
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305)
19:22:30.210
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996)
19:22:30.210
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
19:22:30.210
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at net.minecraft.client.main.Main.main(Main.java:184)
19:22:30.210
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:22:30.210
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
19:22:30.210
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:22:30.210
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at java.lang.reflect.Method.invoke(Method.java:498)
19:22:30.211
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
19:22:30.211
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
19:22:30.211
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
19:22:30.211
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
19:22:30.211
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
19:22:30.211
STDERR
Render thread
[com.tom.cpm.shared.editor.Exporter:lambda$writeOut$11:238]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
`

**Comment by Nues** [comment]
Also in my version, I no longer seem able to right click for move/place or duplicate anymore.

**Comment by Nues** [comment]
Oh I actually finally figured out where the logs are stored... I guess the tutorial I watched taught me wrong.

Here is the full log:

[2021-04-12-2.log](https://github.com/tom5454/CustomPlayerModels/files/6302078/2021-04-12-2.log)

**Comment by tom5454** [comment]
Please try the new version 0.0.12a
