### ISSUE TITLE
 [Render thread/WARN]: Error drawing gui

### ISSUE THREAD

**Issue by foxya27** [tom5454/CustomPlayerModels#683]
[19:25:51] [Render thread/WARN]: Error drawing gui
java.lang.NullPointerException: Cannot read field "x" because "rc.renderScale" is null
	at com.tom.cpm.shared.model.render.ModelRenderManager$RedirectRenderer.translateRotate(ModelRenderManager.java:518) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.tom.cpm.shared.model.render.ModelRenderManager$RedirectRenderer.render(ModelRenderManager.java:544) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.tom.cpm.shared.model.render.DirectModelRenderManager$DirectPartRenderer.doRender0(DirectModelRenderManager.java:228) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.tom.cpm.shared.model.render.ModelRenderManager$RedirectRenderer.lambda$render$0(ModelRenderManager.java:494) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at com.tom.cpm.shared.model.PartRoot.forEach(PartRoot.java:22) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.tom.cpm.shared.model.render.ModelRenderManager$RedirectRenderer.render(ModelRenderManager.java:481) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.tom.cpm.shared.model.render.DirectModelRenderManager$DirectPartRenderer.render(DirectModelRenderManager.java:214) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.tom.cpm.shared.model.builtin.VanillaPlayerModel.render(VanillaPlayerModel.java:82) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.tom.cpm.shared.gui.panel.ViewportPanelBase3d.renderModel(ViewportPanelBase3d.java:134) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.tom.cpm.shared.editor.gui.ViewportPanel.render(ViewportPanel.java:93) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.tom.cpm.client.Panel3dImpl.render(Panel3dImpl.java:70) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.tom.cpm.shared.gui.panel.Panel3d.draw(Panel3d.java:90) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.tom.cpm.shared.editor.gui.ViewportPanel.draw(ViewportPanel.java:127) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.tom.cpl.gui.elements.Panel.draw(Panel.java:33) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.tom.cpl.gui.elements.Panel.draw(Panel.java:33) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.tom.cpl.gui.Frame.draw(Frame.java:88) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.tom.cpm.shared.editor.gui.EditorGui.draw(EditorGui.java:920) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.tom.cpl.gui.Frame.draw(Frame.java:65) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.tom.cpm.client.GuiImpl.lambda$render$1(GuiImpl.java:111) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:720) ~[client-intermediary.jar:?]
	at com.tom.cpm.client.GuiImpl.method_25394(GuiImpl.java:111) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:117) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.mixinextras$bridge$method_47413$191(class_757.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.wrapOperation$zpp000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:913) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1285) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
	
	This model don't load https://discord.com/channels/811508670205788211/811530395240890378/847833934799700009, but 1.20 version load

**Comment by foxya27** [comment]
![image](https://github.com/user-attachments/assets/e5657896-58c9-44e2-afb7-a82c09007d8b)
I have last version CPM

**Comment by KitsuneDev** [comment]
I can reproduce. Happens to me when I try to load my model (which was created in 1.20.4) in 1.21.1

**Comment by Astralneko** [comment]
I can also reproduce. Happens to me when loading the model in 1.21, but not when loading the model in 1.20.

**Comment by KitsuneDev** [comment]
I can also reproduce. Latest version, opening model from 1.20.4.
