### ISSUE TITLE
Skin editor won't work (1.16.5 Fabric)

### ISSUE THREAD

**Issue by gokayerez** [tom5454/CustomPlayerModels#71]
Only fabric, fabric api and cpm.
https://paste.ubuntu.com/p/PrH7pVrh4G/

**Comment by gokayerez** [comment]
**** Here's a better log:


[18:19:54] [main/INFO]: Loading for game Minecraft 1.16.5
[18:19:54] [main/INFO]: [FabricLoader] Loading 48 mods: fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-screen-handler-api-v1@1.1.5+9354966b7d, minecraft@1.16.5, fabric-renderer-api-v1@0.4.2+2868a2287d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabric-command-api-v1@1.1.1+351679a77d, fabricloader@0.11.3, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.7+8183d3957d, fabric-renderer-indigo@0.4.4+ca58154a7d, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.11+9354966b7d, fabric-dimensions-v1@2.0.6+61336ba97d, fabric-object-builder-api-v1@1.9.4+9354966b7d, java@8, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-api-base@0.2.1+9354966b7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-rendering-v1@1.6.0+2868a2287d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-resource-loader-v0@0.4.6+2868a2287d, cpm@0.0.12a, fabric-textures-v0@1.0.6+ca58154a7d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-renderer-registries-v1@2.3.0+2868a2287d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.33.1+1.16, fabric-item-groups-v0@0.2.7+2868a2287d, fabric-models-v0@0.3.0+bc7a746f7d, fabric-particles-v1@0.2.4+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d
[18:19:54] [main/WARN]: Mod `cpm` (0.0.12a) does not respect SemVer - comparison support is limited.
[18:19:54] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/PC/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[18:19:55] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[18:19:58] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:19:59] [main/INFO]: Setting user: Ajan_
[18:19:59] [main/INFO]: [Indigo] Registering Indigo renderer!
[18:20:00] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[18:20:01] [main/INFO]: Narrator library for x64 successfully loaded
[18:20:02] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Fabric Renderer API (v1), Fabric Key Bindings (v0), Fabric Command API (v1), Fabric Loader, Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Structure API (v1), Fabric Containers (v0), Fabric Dimensions API (v1), Fabric Object Builder API (v1), Fabric Events Interaction (v0), Fabric Item API (v1), Fabric Crash Report Info (v1), Fabric Game Rule API (v1), Fabric Entity Events (v1), Fabric API Base, Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Fabric Rendering Data Attachment (v1), Fabric Resource Loader (v0), Customizable Player Models, Fabric Textures (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Fabric Rendering Fluids (v1), Fabric Registry Sync (v0), Fabric Commands (v0), Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Mining Levels (v0), Fabric Renderer Registries (v1), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Loot Tables (v1), Fabric API, Fabric Item Groups (v0), Fabric Models (v0), Fabric Particles (v1), Fabric Object Builders (v0), Fabric Networking (v0), Fabric API Lookup API (v1))
[18:20:07] [main/INFO]: OpenAL initialized.
[18:20:07] [main/INFO]: Sound engine started
[18:20:07] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[18:20:07] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[18:20:07] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[18:20:07] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[18:20:07] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[18:20:07] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[18:20:07] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[18:20:08] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[18:20:08] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[18:20:08] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[18:20:39] [main/INFO]: [STDERR]: java.lang.NullPointerException
[18:20:39] [main/INFO]: [STDERR]: 	at com.tom.cpm.client.ViewportPanelImpl.render(ViewportPanelImpl.java:117)
[18:20:39] [main/INFO]: [STDERR]: 	at com.tom.cpm.shared.editor.gui.ViewportPanel.draw0(ViewportPanel.java:29)
[18:20:39] [main/INFO]: [STDERR]: 	at com.tom.cpm.shared.gui.ViewportPanelBase.draw(ViewportPanelBase.java:44)
[18:20:39] [main/INFO]: [STDERR]: 	at com.tom.cpl.gui.elements.Panel.draw(Panel.java:33)
[18:20:39] [main/INFO]: [STDERR]: 	at com.tom.cpl.gui.elements.Panel.draw(Panel.java:33)
[18:20:39] [main/INFO]: [STDERR]: 	at com.tom.cpl.gui.elements.Panel.draw(Panel.java:33)
[18:20:39] [main/INFO]: [STDERR]: 	at com.tom.cpl.gui.Frame.draw(Frame.java:40)
[18:20:39] [main/INFO]: [STDERR]: 	at com.tom.cpm.client.GuiImpl.method_25394(GuiImpl.java:88)
[18:20:39] [main/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:616)
[18:20:39] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1048)
[18:20:39] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:681)
[18:20:39] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:215)
[18:20:39] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:20:39] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:20:39] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:20:39] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[18:20:39] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[18:20:39] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
[18:20:39] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[18:20:42] [main/INFO]: Stopping!

**Comment by Joe-mama131** [comment]
why was this marked completed?
