### ISSUE TITLE
TypeError: Failed to fetch while exporting

### ISSUE THREAD

**Issue by StakeFromJateFarm** [tom5454/CustomPlayerModels#717]
I got this error and the message said to report it on GitHub so I'm posting the error message here 

Error while exporting:
TypeError: Failed to fetch
    at bXb (PLUGINS/(Plugin):cpm_plugin.js:1772:484)
    at LWb (PLUGINS/(Plugin):cpm_plugin.js:1754:570)
    at p1b (PLUGINS/(Plugin):cpm_plugin.js:1994:42)
    at g2b.h2b [as ie] (PLUGINS/(Plugin):cpm_plugin.js:2021:41)
    at OLe (PLUGINS/(Plugin):cpm_plugin.js:6882:67)
    at o1b (PLUGINS/(Plugin):cpm_plugin.js:1993:23)
    at Function.f2b (PLUGINS/(Plugin):cpm_plugin.js:2020:55)
    at d (PLUGINS/(Plugin):cpm_plugin.js:19:47)
    at new Promise (<anonymous>)
    at c2b.d2b [as Rg] (PLUGINS/(Plugin):cpm_plugin.js:2019:48)
    at z7b (PLUGINS/(Plugin):cpm_plugin.js:2216:32)
    at i1b (PLUGINS/(Plugin):cpm_plugin.js:1987:177)
    at j1b (PLUGINS/(Plugin):cpm_plugin.js:1988:62)
    at Function.p4b (PLUGINS/(Plugin):cpm_plugin.js:2097:52)
    at Codec.d (PLUGINS/(Plugin):cpm_plugin.js:19:47)
    at Function.gTb (PLUGINS/(Plugin):cpm_plugin.js:1657:63)
    at Action.d [as onClick] (PLUGINS/(Plugin):cpm_plugin.js:19:47)
    at Action.click (file:///C:/Users/kobol/AppData/Local/Programs/Blockbench/resources/app.asar/js/interface/actions.js:268:10)
    at Action.trigger (file:///C:/Users/kobol/AppData/Local/Programs/Blockbench/resources/app.asar/js/interface/actions.js:335:10)
    at HTMLLIElement.<anonymous> (file:///C:/Users/kobol/AppData/Local/Programs/Blockbench/resources/app.asar/js/interface/actions.js:294:10)

**Comment by StakeFromJateFarm** [comment]
For whatever reason, just closing Blockbench, leaving it for a few hours, and coming back seems to have fixed it. I'm not sure how
